project_id = "gxdmanskjvslganqcplr"

[functions.validate-attendance]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.execute-code]
verify_jwt = false

[functions.check-plagiarism]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false
