project_id = "gxdmanskjvslganqcplr"

[functions.validate-attendance]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false
